license = "GNU GPLv3"
modLoader = "javafml"
loaderVersion = "[40,)"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "Paulem"
description = "${description}"

logoFile = "assets/oushii/icon.png"

[[mixins]]
config = "oushii.mixins.json"

[[mixins]]
config = "oushii.client.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"